name: CI/CD Pipeline with Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner instead of GitHub-hosted
    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t nextjs-app:latest .

      # Step 3: Push Docker Image
      - name: Push Docker Image
        run: |
          docker tag nextjs-app:latest ankitojha2705/nextjs-app:latest
          docker push ankitojha2705/nextjs-app:latest

      # Step 4: Deploy the Application Locally
      - name: Run Docker Container
        run: |
          docker stop nextjs-app || true
          docker rm nextjs-app || true
          docker run -d --name nextjs-app -p 3000:3000 nextjs-app:latest
